const verbs = [
  ['to love', 'amō', 'amāre', 'amāvī', 'amātus'],
  ['to have', 'habēo', 'habēre', 'habuī', 'habitus'],
  ['to send', 'mittō', 'mittere', 'mīsī', 'missus'],
  ['to throw', 'iaciō', 'iacere', 'iēcī', 'iactus'],
  ['to hear', 'audiō', 'audīre', 'audīvī', 'audītus'],
];

const tenses = [
  {
    name: 'present',
    pp: 1,
    descriptions: [
      'loves, is loving',
      'has, is having',
      'sends, is sending',
      'throws, is throwing',
      'hears, is hearing',
    ],
    examples: [
      [
        ['am|ō', 'amā|s', 'ama|t', 'amā|mus', 'amā|tis', 'ama|nt'],
        [
          'I love',
          'you love',
          'he loves',
          'we love',
          'you all love',
          'they love',
        ],
      ],
      [
        ['habe|ō', 'habē|s', 'habe|t', 'habē|mus', 'habē|tis', 'habe|nt'],
        [
          'I have',
          'you have',
          'he has',
          'we have',
          'you all have',
          'they have',
        ],
      ],
      [
        ['mitt|ō', 'mitti|s', 'mitti|t', 'mitti|mus', 'mitti|tis', 'mittu|nt'],
        [
          'I send',
          'you send',
          'he sends',
          'we send',
          'you all send',
          'they send',
        ],
      ],
      [
        ['iaci|ō', 'iaci|s', 'iaci|t', 'iaci|mus', 'iaci|tis', 'iaciu|nt'],
        [
          'I throw',
          'you throw',
          'he throws',
          'we throw',
          'you all throw',
          'they throw',
        ],
      ],
      [
        ['audi|ō', 'audī|s', 'audi|t', 'audī|mus', 'audī|tis', 'audiu|nt'],
        [
          'I hear',
          'you hear',
          'he hears',
          'we hear',
          'you all hear',
          'they hear',
        ],
      ],
    ],
  },
  {
    name: 'imperfect',
    pp: 1,
    descriptions: [
      'was loving, kept loving, used to love',
      'was having, kept having, used to have',
      'was sending, kept sending, used to send',
      'was throwing, kept throwing, used to throw',
      'was hearing, kept hearing, used to hear',
    ],
    examples: [
      [
        ['amā|bam', 'amā|bās', 'amā|bat', 'amā|bāmus', 'amā|bātis', 'amā|bant'],
        [
          'I was loving',
          'you were loving',
          'he was loving',
          'we were loving',
          'you all were loving',
          'they were loving',
        ],
      ],
      [
        [
          'habe|bam',
          'habē|bās',
          'habe|bat',
          'habē|bāmus',
          'habē|bātis',
          'habe|bant',
        ],
        [
          'I was having',
          'you were having',
          'he was having',
          'we were having',
          'you all were having',
          'they were having',
        ],
      ],
      [
        [
          'mittē|bam',
          'mittē|bās',
          'mittē|bat',
          'mittē|bāmus',
          'mittē|bātis',
          'mittēba|nt',
        ],
        [
          'I was sending',
          'you were sending',
          'he was sending',
          'we were sending',
          'you all were sending',
          'they were sending',
        ],
      ],
      [
        [
          'iaciē|bam',
          'iacē|bās',
          'iaciē|bat',
          'iaciē|bāmus',
          'iaciē|bātis',
          'iaciē|bant',
        ],
        [
          'I was throwing',
          'you were throwing',
          'he was throwing',
          'we were throwing',
          'you all were throwing',
          'they were throwing',
        ],
      ],
      [
        [
          'audiē|bam',
          'audiē|bās',
          'audiē|bat',
          'audiē|bāmus',
          'audiē|bātis',
          'audiē|bānt',
        ],
        [
          'I was hearing',
          'you were hearing',
          'he was hearing',
          'we were hearing',
          'you all were hearing',
          'they were hearing',
        ],
      ],
    ],
  },
  {
    name: 'future',
    pp: 1,
    descriptions: [
      'will love, shall love',
      'will have, shall have',
      'will send, shall send',
      'will throw, shall throw',
      'will hear, shall hear',
    ],
    examples: [
      [
        ['amā|bo', 'amā|bis', 'amā|bit', 'amā|bimus', 'amā|bitis', 'amā|bunt'],
        [
          'I will love',
          'you will love',
          'he will love',
          'we will love',
          'you all will love',
          'they will love',
        ],
      ],
      [
        [
          'habe|bo',
          'habē|bis',
          'habe|bit',
          'habē|bimus',
          'habē|bitis',
          'habe|bunt',
        ],
        [
          'I will have',
          'you will have',
          'he will have',
          'we will have',
          'you all will have',
          'they will have',
        ],
      ],
      [
        ['mitt|am', 'mitt|ēs', 'mitt|et', 'mitt|ēmus', 'mitt|ētis', 'mitt|ent'],
        [
          'I will send',
          'you will send',
          'he will send',
          'we will send',
          'you all will send',
          'they will send',
        ],
      ],
      [
        ['iaci|am', 'iac|ēs', 'iaci|ēt', 'iaci|ēmus', 'iaci|ētis', 'iaci|ent'],
        [
          'I will throw',
          'you will throw',
          'he will throw',
          'we will throw',
          'you all will throw',
          'they will throw',
        ],
      ],
      [
        ['audi|am', 'audi|ēs', 'audi|ēt', 'audi|ēmus', 'audi|ētis', 'audi|ēnt'],
        [
          'I was hearing',
          'you were hearing',
          'he was hearing',
          'we were hearing',
          'you all were hearing',
          'they were hearing',
        ],
      ],
    ],
  },
  {
    name: 'perfect',
    pp: 2,
    descriptions: [
      'loved, has loved',
      'had, has had',
      'sent, has sent',
      'threw, has thrown',
      'heard, has heard',
    ],
    examples: [
      [
        [
          'amāv|ī',
          'amāv|istī',
          'amāv|it',
          'amāv|imus',
          'amāv|istis',
          'amāv|ērunt',
        ],
        [
          'I loved',
          'you loved',
          'he loved',
          'we loved',
          'you all loved',
          'they loved',
        ],
      ],
      [
        [
          'habu|ī',
          'habu|istī',
          'habu|it',
          'habu|imus',
          'habu|itis',
          'habu|ērunt',
        ],
        ['I had', 'you had', 'he had', 'we had', 'you all had', 'they had'],
      ],
      [
        ['mīs|ī', 'mīs|istī', 'mīs|it', 'mīs|imus', 'mīs|istis', 'mīs|ērunt'],
        ['I sent', 'you sent', 'he sent', 'we sent', 'you sent', 'they sent'],
      ],
      [
        ['iēc|ī', 'iēc|istī', 'iēc|it', 'iēc|imus', 'iēc|istis', 'iēc|ērunt'],
        [
          'I threw',
          'you threw',
          'he threw',
          'we threw',
          'you all threw',
          'they threw',
        ],
      ],
      [
        ['audīv|ī', 'audīv|istī', 'audīv|it', 'audīv|imus', 'audīv|istis', 'audīv|ērunt'],
        [
          'I was hearing',
          'you were hearing',
          'he was hearing',
          'we were hearing',
          'you all were hearing',
          'they were hearing',
        ],
      ],
    ],
  },
  {
    name: 'pluperfect',
    pp: 2,
    descriptions: [
      'had loved',
      'had had',
      'had sent',
      'had thrown',
      'had heard',
    ],
    examples: [
      [
        [
          'amāv|eram',
          'amāv|erās',
          'amāv|erat',
          'amāv|erāmus',
          'amāv|erātis',
          'amāv|erant',
        ],
        [
          'I had loved',
          'you had loved',
          'he had loved',
          'we had loved',
          'you all had loved',
          'they had loved',
        ],
      ],
      [
        [
          'habu|eram',
          'habu|erās',
          'habu|erat',
          'habu|erāmus',
          'habu|erātis',
          'habu|erant',
        ],
        [
          'I had had',
          'you had had',
          'he had had',
          'we had had',
          'you all had had',
          'they had had',
        ],
      ],
      [
        [
          'mīs|eram',
          'mīs|erās',
          'mīs|erat',
          'mīs|erāmus',
          'mīs|erātis',
          'mīs|erant',
        ],
        [
          'I had sent',
          'you had sent',
          'he had sent',
          'we had sent',
          'you had sent',
          'they had sent',
        ],
      ],
      [
        [
          'iēc|eram',
          'iēc|erās',
          'iēc|erat',
          'iēc|erāmus',
          'iēc|erātis',
          'iēc|erant',
        ],
        [
          'I had thrown',
          'you had thrown',
          'he had thrown',
          'we had thrown',
          'you all had thrown',
          'they had thrown',
        ],
      ],
      [
        [
          'audiv|eram',
          'audiv|erās',
          'audiv|erat',
          'audiv|erāmus',
          'audiv|erātis',
          'audiv|erant',
        ],
        [
          'I had heard',
          'you had heard',
          'he had heard',
          'we had heard',
          'you all had heard',
          'they had heard',
        ],
      ],
    ],
  },
  {
    name: 'future perfect',
    pp: 2,
    descriptions: [
      'will have loved',
      'will have had',
      'will have sent',
      'will have thrown',
      'will have heard',
    ],
    examples: [
      [
        [
          'amāv|erō',
          'amāv|eris',
          'amāv|erit',
          'amāv|erimus',
          'amāv|eritis',
          'amāv|erint',
        ],
        [
          'I will have loved',
          'you will have loved',
          'he will have loved',
          'we will have loved',
          'you all will have loved',
          'they will have loved',
        ],
      ],
      [
        [
          'habu|erō',
          'habu|eris',
          'habu|erit',
          'habu|erimus',
          'habu|eritis',
          'habu|erint',
        ],
        [
          'I will have had',
          'you will have had',
          'he will have had',
          'we will have had',
          'you all will have had',
          'they will have had',
        ],
      ],
      [
        [
          'mīs|erō',
          'mīs|eris',
          'mīs|erit',
          'mīs|erimus',
          'mīs|eritis',
          'mīs|erint',
        ],
        [
          'I will have sent',
          'you will have sent',
          'he will have sent',
          'we will have sent',
          'you will have sent',
          'they will have sent',
        ],
      ],
      [
        [
          'iēc|erō',
          'iēc|eris',
          'iēc|erit',
          'iēc|erimus',
          'iēc|eritis',
          'iēc|erint',
        ],
        [
          'I will have thrown',
          'you will have thrown',
          'he will have thrown',
          'we will have thrown',
          'you all will have thrown',
          'they will have thrown',
        ],
      ],
      [
        [
          'audiv|erō',
          'audiv|eris',
          'audiv|erit',
          'audiv|erimus',
          'audiv|eritis',
          'audiv|erint',
        ],
        [
          'I will have heard',
          'you will have heard',
          'he will have heard',
          'we will have heard',
          'you all will have heard',
          'they will have heard',
        ],
      ],
    ],
  },
];

export default { tenses, verbs };
